Vagrant.configure("2") do |config|
  # Define VM for Spectre Web (Junaid)
  config.vm.define "spectre_web" do |web_config|
    web_config.vm.box = "ubuntu/bionic64"
    web_config.vm.network "forwarded_port", guest: 80, host: 8080
    web_config.vm.network "private_network", type: "dhcp"
    web_config.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/application1_playbook.yml"
      ansible.extra_vars = { app_name: "spectre_web" }
    end
  end

  # Define VM for Spectre Android (Haram)
  config.vm.define "spectre_android" do |android_config|
    android_config.vm.box = "ubuntu/bionic64"
    android_config.vm.network "forwarded_port", guest: 8080, host: 8081
    android_config.vm.network "private_network", type: "dhcp"
    android_config.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/application2_playbook.yml"
      ansible.extra_vars = { app_name: "spectre_android" }
    end
  end
end
