---
- hosts: all
  become: true

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install dependencies for Spectre Web
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - python3
        - python3-pip

    - name: Install Spectre Web application
      pip:
        name: spectre-web
        state: present

    - name: Configure Nginx for Spectre Web
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/spectre-web
      notify:
        - Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

