---
- hosts: all
  become: true

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install dependencies for Spectre Android
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - openjdk-8-jdk
        - android-sdk
        - unzip

    - name: Set up Spectre Android environment variables
      lineinfile:
        path: ~/.bashrc
        line: |
          export ANDROID_HOME=/usr/lib/android-sdk
          export PATH=$PATH:$ANDROID_HOME/tools
          export PATH=$PATH:$ANDROID_HOME/tools/bin
          export PATH=$PATH:$ANDROID_HOME/platform-tools
      become_user: haram
      become_method: su

    - name: Download and install Android SDK components
      command: "{{ item }}"
      loop:
        - "sdkmanager --update"
        - "sdkmanager 'platform-tools' 'build-tools;29.0.3' 'platforms;android-29' 'system-images;android-29;google_apis;x86_64'"

    - name: Create and start Android emulator
      command: "echo 'no' | avdmanager create avd --force --name testAVD --abi google_apis/x86_64 --package 'system-images;android-29;google_apis;x86_64'"
      become_user: haram
      become_method: su

    - name: Start the Android emulator
      command: "emulator -avd testAVD -no-skin -no-audio -no-window -gpu off &"
      become_user: haram
      become_method: su

    - name: Wait for the emulator to start
      wait_for:
        host: localhost
        port: 5554
        state: started
        delay: 30
        timeout: 120

    - name: Install Spectre Android application
      command: "/path/to/spectre-android-install.sh"
      become_user: haram
      become_method: su

